- hosts: all
  gather_facts: false 

  vars:
    debian_distro : "bullseye"
    ubuntu_distro : "focal"
    decidim_app_repository: "{{ git_root }}/{{ git_organization }}/{{ git_repository }}"
    decidim_app_directory: "{{ decidim_deployment_path }}/{{ git_repository }}"
    postgresql_version: "13"
    postgresql_bin_path: "/usr/lib/postgresql/{{ postgresql_version }}/bin"
    postgresql_data_dir: "/var/lib/postgresql/{{ postgresql_version }}/main"
    nodejs_version: "16"
        
  roles:
    - decidim_install