- name: Decidim | Moderation - Remove from search
  shell:
    cmd: "RAILS_ENV=production {{ decidim_deployment_path }}/.rbenv/shims/bundle exec rails decidim:upgrade:moderation:remove_from_search"
    chdir: "{{ decidim_app_directory }}"

- name: Decidim | Update participatory process in comments
  shell:
    cmd: "RAILS_ENV=production {{ decidim_deployment_path }}/.rbenv/shims/bundle exec rake decidim_comments:update_participatory_process_in_comments"
    chdir: "{{ decidim_app_directory }}"

- name: Decidim | Migrate from carrierwave to Active Storage
  shell:
    cmd: "RAILS_ENV=production {{ decidim_deployment_path }}/.rbenv/shims/bundle exec rails decidim:active_storage_migrations:migrate_from_carrierwave_to_active_storage"
    chdir: "{{ decidim_app_directory }}"

- name: Decidim | Migrate from inline images to Active Storage
  shell:
    cmd: "RAILS_ENV=production {{ decidim_deployment_path }}/.rbenv/shims/bundle exec rails decidim:active_storage_migrations:migrate_inline_images_to_active_storage[{{ decidim_admin_email }}]"
    chdir: "{{ decidim_app_directory }}"

- name: Decidim | Update search index for users
  shell:
    cmd: "RAILS_ENV=production {{ decidim_deployment_path }}/.rbenv/shims/bundle exec rails runner 'Decidim::User.find_each(&:try_update_index_for_search_resource)'"
    chdir: "{{ decidim_app_directory }}"

- name: Decidim | Update search index for user groups
  shell:
    cmd: "RAILS_ENV=production {{ decidim_deployment_path }}/.rbenv/shims/bundle exec rails runner 'Decidim::UserGroup.find_each(&:try_update_index_for_search_resource)'"
    chdir: "{{ decidim_app_directory }}"

- name: NGINX | Restart NGINX
  systemd:
    state: restarted
    daemon_reload: yes
    name: nginx
  become: true

- name: Sidekiq | Restart sidekiq
  systemd:
    state: restarted
    daemon_reload: yes
    name: sidekiq
  become: true
