- name: Certbot | Install packages
  apt:
    name:
    - certbot
    - python3-certbot-nginx
    state: latest
  become: true

- name: Certbot | Create SSL certificate
  shell: 
    cmd: "certbot run -n --nginx --agree-tos 
                      -d {{ decidim_host }}
                      -m  {{ certbot_email_address }} 
                      --redirect"
  become: true

- name: Certbot | Restart Nginx
  systemd:
    state: restarted
    name: nginx
  become: true

