- name: Nginx | Install Nginx
  apt:
    name: 
      - nginx
      - nginx-extras
    state: latest
  become: true

- name: Nginx | Start and enable service Nginx
  ansible.builtin.systemd:
    name: nginx
    state: started
    enabled: yes
  become: true

- name: Nginx | Create vhost sites
  template:
    src: templates/nginx-decidim.j2
    dest: "/etc/nginx/sites-available/decidim"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0664"
  become: true

- name: Nginx | Check if default site is enabled
  stat:
    path: /etc/nginx/sites-enabled/default
  register: niginx_sites_default
  become: true

- name: Nginx | Remove default sites
  shell: 
    cmd: sudo rm /etc/nginx/sites-enabled/default
  become: true
  when : niginx_sites_default.stat.exists

- name: Nginx | Enabled vhost sites
  shell: 
    cmd: sudo ln -sfv /etc/nginx/sites-available/decidim /etc/nginx/sites-enabled/
  become: true

- name: Nginx | Add execution permission to decidim user
  shell:
    cmd: "chmod g+x,o+x {{ decidim_deployment_path }}/"
  become: true
